services:
  netbox:
    ports:
      - "8082:8080"
    volumes:
    - /home/gekkoadmin/netbox/configuration:/etc/netbox/config:z,rw
    - netbox-media-files:/opt/netbox/netbox/media
    - netbox-reports-files:/opt/netbox/netbox/reports
    - netbox-scripts-files:/opt/netbox/netbox/scripts
    healthcheck:
      retries: 15
  netbox-worker:
    volumes:
    - /home/gekkoadmin/netbox/configuration:/etc/netbox/config:z,rw
    - netbox-media-files:/opt/netbox/netbox/media
    - netbox-reports-files:/opt/netbox/netbox/reports
    - netbox-scripts-files:/opt/netbox/netbox/scripts
  netbox-housekeeping:
    volumes:
    - /home/gekkoadmin/netbox/configuration:/etc/netbox/config:z,rw
    - netbox-media-files:/opt/netbox/netbox/media
    - netbox-reports-files:/opt/netbox/netbox/reports
    - netbox-scripts-files:/opt/netbox/netbox/scripts
    environment:
      SKIP_SUPERUSER: "false"
      # SUPERUSER_API_TOKEN: ""
      # SUPERUSER_EMAIL: ""
      # SUPERUSER_NAME: ""
      # SUPERUSER_PASSWORD: ""
